---
- name: Initialize ServerLedge Workflows
  hosts: client
  
  vars:
    serverledge_cli: "serverledge/serverledge-cli"
    serverledge_host: "{{ hostvars[groups['edge'][0]]['private_ip'] }}"
    serverledge_port: "1323"
    
    workflows:
      - name: weatherApp
        json_file: "src/weather/weather.json"
        func_create_cmds:
          - "create -u -f weather --memory 500 --runtime custom --custom_image grussorusso/weatherfunc --input gemini_api_key:Text --input latitude:Float --input longitude:Float --output gemini_api_key:Text --output current_temperature:Float --output daily_rain_sum:ArrayFloat --output daily_max_temp:ArrayFloat --output daily_min_temp:ArrayFloat"
          - "create -u -f adapter --memory 200 --runtime python310 --handler adapter.handler --src /root/src/weather/adapter.py --input gemini_api_key:Text --input current_temperature:Float --input daily_rain_sum:ArrayFloat --input daily_max_temp:ArrayFloat --input daily_min_temp:ArrayFloat --output prompt:Text --output gemini_api_key:Text"
          - "create -u -f gemini --memory 500 --runtime custom --custom_image grussorusso/geminifunc --input gemini_api_key:Text --input prompt:Text --output response:Text"
      
      - name: sentimentAnalysis
        json_file: "src/sentiment/workflow.json"
        func_create_cmds:
          - "create -u --function sa_retrieve --memory 256 --runtime custom --custom_image matnar/sa-retrieve --input data_url:Text --input local_dir:Text --input object_name:Text --output status:Text --output local_download:Bool --output uploaded:Bool --output object_name:Text"
          - "create -u --function sa_extract --memory 256 --runtime custom --custom_image matnar/sa-extract --input tgz_input_object_name:Text --input subset:Float --input local_dataset_file:Text --input local_output_dir:Text --input output_train_object_name:Text --input output_test_object_name:Text --output status:Text --output train_object_name:Text --output test_object_name:Text"
          - "create -u --function sa_train --memory 1224 --runtime custom --custom_image matnar/sa-train --input subset:Float --input max_features:Int --input train_object_data:Text --input local_train_file:Text --input local_model_file:Text --input local_vectorizer_file:Text --input output_model_object:Text --input output_vectorizer_object:Text --output status:Text --output model_object_name:Text --output vectorizer_object_name:Text"
          - "create -u --function sa_evaluate --memory 512 --runtime custom --custom_image matnar/sa-evaluate --input test_object_data:Text --input local_test_file:Text --input subset:Float --input local_model_file:Text --input local_vectorizer_file:Text --input input_model_object:Text --input input_vectorizer_object:Text --output status:Text --output accuracy:Float"

  tasks:
    - name: Process each workflow
      include_tasks: create_functions_and_workflows_tasks.yml
      loop: "{{ workflows }}"
      loop_control:
        loop_var: workflow_item
