---
- name: Install Docker
  hosts: 
    - edge
    - cloud

  tasks:
    - name: "Install Docker using role"
      include_role:
        role: geerlingguy.docker
      when: ansible_facts['distribution'] != "Amazon"

    - name: "Install Docker on Amazon Linux"
      block:
        - name: Check for Docker
          ansible.builtin.shell: "docker ps > /dev/null"
          register: check
          ignore_errors: True

        - name: Install Docker
          ansible.builtin.command: amazon-linux-extras install -y docker
          become: yes
          when: check.failed

        - name: Start docker
          ansible.builtin.command: systemctl start docker
          become: yes
      when: ansible_facts['distribution'] == "Amazon"


    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        append: yes
        groups: docker
      become: yes

    - name: reset ssh connection
      meta: reset_connection
      when: groupupdated

- name: Install Etcd
  hosts: cloud[0]
  roles:
    - role: etcd
      wipe_etcd: true



- name: Install ServerlEdge at the Edge
  hosts: edge
  vars:
    conf_template: edge-configuration.yaml.j2

  roles:
    - serverledge

- name: Install ServerlEdge in all Cloud nodes
  hosts: cloud
  vars:
    conf_template: cloud-configuration.yaml.j2
  tasks:
    - include_role: 
        name: serverledge
      when: groups['cloud'] | length | int < 2

- name: Install ServerlEdge in all Cloud nodes but one
  hosts: cloud[1:]
  vars:
    conf_template: cloud-configuration.yaml.j2
  tasks:
    - include_role: 
        name: serverledge
      when: groups['cloud'] | length | int > 1

- name: Install LB in the Cloud
  hosts: cloud[0]
  vars: 
    conf_template: lb-configuration.yaml.j2

  tasks:
    - include_role: 
        name: serverledge_lb
      when: groups['cloud'] | length | int > 1

- name: Install Prometheus in one of the Edge nodes
  hosts: edge[-1]
  vars: 
    conf_template: prometheus-configuration.yaml.j2

  tasks:
    - include_role: 
        name: prometheus
      when: deploy_prometheus


- name: Install ILP Solver in one of the Edge nodes
  hosts: edge[0]

  tasks:
    - ansible.builtin.apt:
        name: glpk-utils
        state: present
    - ansible.builtin.apt:
        name: python3-pulp
        state: present
    - ansible.builtin.apt:
        name: python3-numpy
        state: present

    - ansible.builtin.file:
        path: "/root/solver"
        state: directory
        mode: '0755'

    - ansible.posix.synchronize:
        src: /home/gabriele/Dev/workflow-offloading/
        dest: /root/solver/
        rsync_opts:
          - "--exclude=env"

    - name: copy systemd unit file
      become: yes 
      copy:
        src: "/root/solver/solver.service"
        dest: "/etc/systemd/system/"
        remote_src: True

    - name: enable and start systemd service
      become: yes 
      systemd:
        daemon_reload: yes
        state: restarted
        name: "solver.service"
        enabled: yes


