---
- name: Restart Serverledge
  hosts: 
    - edge
    - cloud[1:]
  tasks:
    - include_tasks:
        file: tasks/restart_serverledge.yml

- name: Quick benchmark
  hosts: 
    - client
  vars:
    profiling_script: "./profile_workflows.py"
    inputs_dir: "./saved-inputs"
    src_dir: "./locust/src"

  tasks:
    - name: Copy profiling script
      ansible.builtin.copy:
        src: "{{ profiling_script }}"
        dest: "."

    - name: Copy workflow JSON files
      ansible.builtin.copy:
        src: "{{ src_dir }}/sentiment/workflow.json"
        dest: "sentiment.json"

    - name: Copy workflow JSON files
      ansible.builtin.copy:
        src: "{{ src_dir }}/weather/weather.json"
        dest: "weather.json"

    - name: Copy workflow JSON files
      ansible.builtin.copy:
        src: "{{ src_dir }}/person-detection/workflow.json"
        dest: "personDetection.json"

    - name: Ensure destination directory exists
      file:
        path: "saved-inputs"
        state: directory
        mode: '0755'
       
    - name: Sync directory to remote server
      synchronize:
        src: "{{ inputs_dir }}/"
        dest: "./saved-inputs/"
        delete: yes
        recursive: yes
        #
        #
    - name: Find JSON files across multiple directories
      ansible.builtin.find:
        paths:
          - saved-inputs/sa_extract
          - saved-inputs/sa_evaluate
          - saved-inputs/sa_train
          - saved-inputs/sa_retrieve
        patterns:
          - "*.json"
        recurse: yes
      register: json_files_to_modify

    # XXX: necessary to update MinIO IP in the workflow input files
    - name: Update minio_endpoint in all JSON files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '"minio_endpoint"\s*:\s*"[^"]*"'
        replace: '"minio_endpoint":"{{ hostvars[groups["cloud"][0]]["ansible_host"] }}:9000"'
      loop: "{{ json_files_to_modify.files }}"


    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep grussorusso | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True
    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep matnar | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True


      # NOTE: we only target cloud[0] == the load balancer
#    - name: Start 
#      ansible.builtin.shell: "#python3 profile_workflows.py -w sentiment.json weather.json personDetection.json -i saved-inputs -e {% for host in groups['edge'] %} http://{{ hostvars[host]['private_ip'] }}:1323 {% endfor %} http://{{ hostvars[groups['cloud'][0]]['private_ip'] }}:1325"
#      async: 900
#      poll: 20
#      register: locust_out

    - name: Start workflow profiling
      ansible.builtin.shell: >
        python3 profile_workflows.py
        -w {{ item }}
        -i saved-inputs
        -e {% for host in groups['edge'] %} http://{{ hostvars[host]['private_ip'] }}:1323 {% endfor %}
        http://{{ hostvars[groups['cloud'][0]]['private_ip'] }}:1325
      loop:
        - sentiment.json
        - weather.json
        - personDetection.json

