---
- name: Restart Serverledge
  hosts: 
    - edge
    - cloud
  tasks:
    - include_tasks:
        file: tasks/restart_serverledge.yml

    - ansible.builtin.command: docker pull grussorusso/weatherfunc
    - ansible.builtin.command: docker pull grussorusso/geminifunc
    - ansible.builtin.command: docker pull matnar/sa-retrieve
    - ansible.builtin.command: docker pull matnar/sa-extract
    - ansible.builtin.command: docker pull matnar/sa-train
    - ansible.builtin.command: docker pull matnar/sa-evaluate

- name: Quick benchmark
  hosts: 
    - client
  vars:
    profiling_script: "./profile_workflows.py"
    inputs_dir: "./saved-inputs"
    src_dir: "./locust/src"

  tasks:
    - name: Copy profiling script
      ansible.builtin.copy:
        src: "{{ profiling_script }}"
        dest: "."

    - name: Copy workflow JSON files
      ansible.builtin.copy:
        src: "{{ src_dir }}/sentiment/workflow.json"
        dest: "sentiment.json"

    - name: Copy workflow JSON files
      ansible.builtin.copy:
        src: "{{ src_dir }}/weather/weather.json"
        dest: "weather.json"

    - name: Ensure destination directory exists
      file:
        path: "saved-inputs"
        state: directory
        mode: '0755'

    - name: Sync directory to remote server
      synchronize:
        src: "{{ inputs_dir }}/"
        dest: "./saved-inputs/"
        delete: yes
        recursive: yes

    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep grussorusso | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True
    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep matnar | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True

    - name: Start 
      ansible.builtin.shell: "python3 profile_workflows.py -w sentiment.json -w weather.json -i saved-inputs {% for host in groups['edge'] %}-e http://{{ hostvars[host]['private_ip'] }}:1323 {% endfor %}"
      async: 900
      poll: 20
      register: locust_out

    - debug:
        var: locust_out.stdout_lines

- name: Update saved profiling data 
  hosts: 
    - edge[0]

  tasks:
    - name: Backup previous profiling data
      ansible.builtin.copy:
        src: "solver/saved.pickle"
        dest: "solver/savedOLD.pickle"
        remote_src: true

    - name: Update profiling data
      ansible.builtin.copy:
        src: "solver/savedNEW.pickle"
        dest: "solver/saved.pickle"
        remote_src: true
