---
- name: Restart Serverledge
  hosts: 
    - edge
    - cloud
  tasks:
    - include_tasks:
        file: tasks/restart_serverledge.yml

    - ansible.builtin.command: docker pull grussorusso/weatherfunc

    #- name: Install CPU monitoring script
    #  ansible.builtin.copy:
    #    src: monitorCPU.sh
    #    dest: "{{ ansible_env.HOME }}"
    #    mode: '0755'

    #- name: Install CPU monitoring service
    #  ansible.builtin.template:
    #    src: monitorCPU.service.j2
    #    dest: /etc/systemd/system/monitorCPU.service
    #    owner: root
    #    group: root
    #  become: yes
    #  register: monitor_service
#
#    - name: Reload systemd
#      ansible.builtin.systemd:
#        daemon_reload: yes
#      become: yes
#      when: monitor_service.changed
#
#    - name: Start systemd service
#      ansible.builtin.systemd:
#        name: monitorCPU
#        state: restarted
#      become: yes

- name: Quick benchmark
  hosts: 
    - client
  vars:
    locustfile: locust/locustfile.py

  tasks:
    - name: Install Locust
      include_role:
        role: locust

    - name: Install serverledge-cli
      include_role:
        role: serverledge
      vars:
        deploy_cli_only: true

    - ansible.builtin.copy:
        src: files/hello.py
        dest: "{{ ansible_env.HOME }}/hello.py"

    - name: Copy locustfile
      ansible.builtin.copy:
        src: "{{ locustfile }}"
        dest: ./locustfile.py

    - name: Clean previous results
      ansible.builtin.shell: "rm /tmp/jmeter*"
      ignore_errors: True

    - name: Stop any running Locust instance
      ansible.builtin.shell: "pgrep locust | xargs kill -TERM"
      ignore_errors: True

    - name: Start 
      ansible.builtin.shell: "locust --headless --csv locustresult --json-file locustjson --run-time 30 -H http://{{ hostvars[groups['edge'][0]]['private_ip'] }}:1323"
      async: 900
      poll: 20
      register: locust_out

    #- name: Zip Response files
    #  community.general.archive:
    #    path:
    #      - jmeterResponse_*
    #    dest: /tmp/jmeter_responses.tar.gz
    #    format: gz
    #    remove: yes

    #- name: Copy results
    #  ansible.builtin.fetch: 
    #    src: /tmp/jmeter_results
    #    dest: "{{ local_results_file }}"
    #    flat: yes

    #- name: Copy responses
    #  ansible.builtin.fetch: 
    #    src: /tmp/jmeter_responses.tar.gz
    #    dest: "{{ local_responses_file }}"
    #    flat: yes

    - debug:
        var: locust_out.stdout_lines

