---
- name: Update Edge Serverledge configuration
  hosts: 
    - edge
  tasks:
    - name: Update Edge Serverledge configuration before restart
      ansible.builtin.template:
        src: edge-configuration.yaml.j2
        dest: "serverledge/conf.yml"
        owner: root
        group: root
      become: yes

- name: Restart Serverledge
  hosts: 
    - edge
    - cloud[1:]
  tasks:
    - include_tasks:
        file: tasks/restart_serverledge.yml

    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep grussorusso | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True
    - name: Kill all running Docker containers
      ansible.builtin.shell: "docker ps | grep matnar | cut -d ' ' -f 1 | grep -v CONT | xargs docker kill"
      become: yes
      ignore_errors: True
    - name: Prune Docker containers
      ansible.builtin.shell: "docker container prune -f"
      become: yes
      ignore_errors: True



- name: Restore profiled metrics
  hosts:
    - edge[0]
  tasks:
    - ansible.builtin.copy:
        src: "profiled_metrics.json"
        dest: "/tmp/"

- name: Set variable for local result directory
  hosts: localhost
  gather_facts: true
  vars:
    local_results_dir: results
  tasks:
    - name: Add timestamp to directory name for results
      set_fact:
        local_results_dir_with_ts: "{{ local_results_dir }}-{{ ansible_date_time.iso8601_basic_short }}"




- name: Quick benchmark
  hosts: 
    - client
  vars:
    local_results_dir: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}"
    duration_sec: 240
    num_users: 5
  gather_facts: True

  tasks:
    - name: Install Locust
      include_role:
        role: locust

    - name: Copy locust dir
      ansible.builtin.copy:
        src: "locust/"
        dest: "."

    # XXX: necessary to update MinIO IP in the workflow input files
    - name: Update minio_endpoint in all JSON files
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '("minio_endpoint":\s*")[^"]*(")'
        replace: '\1{{ hostvars[groups["cloud"][0]]["ansible_host"] }}:9000\2'
      with_fileglob:
        - locust/input/sentiment*.json

    - name: Clean previous results
      ansible.builtin.shell: "rm locust-results*"
      ignore_errors: True

    - name: Stop any running Locust instance
      ansible.builtin.shell: "pgrep locust | xargs kill -TERM"
      ignore_errors: True

    - name: Start 
      ansible.builtin.shell: "locust --headless --skip-log --csv locust-results --json --run-time {{ duration_sec }} --stop-timeout 10s --users {{ num_users }} -H http://{{ hostvars[groups['edge'][0]]['private_ip'] }}:1323"
      
      async: 900
      poll: 20
      ignore_errors: True
      register: locust_out

    - name: Save Locust output to file
      copy:
        content: "{{ locust_out.stdout }}"
        dest: locust-results_stdout.json

    - name: Save Locust stderr to file
      copy:
        content: "{{ locust_out.stderr }}"
        dest: locust-results_stderr.json

    #- name: Zip Response files
    #  community.general.archive:
    #    path:
    #      - responses/*
    #    dest: /tmp/responses.tar.gz
    #    format: gz
    #    remove: yes
    #- name: Copy responses
    #  ansible.builtin.fetch: 
    #    src: /tmp/responses.tar.gz
    #    dest: "{{ local_results_dir }}/responses.tar.gz"
    #    flat: yes

    - name: Copy results
      ansible.builtin.fetch: 
        src: "{{ item }}"
        dest: "{{ local_results_dir }}/"
        flat: yes
      with_list:
        - "locust-results_exceptions.csv"
        - "locust-results_failures.csv"
        - "locust-results_stats.csv"
        - "locust-results_stats_history.csv"
        - "locust-results_stdout.json"
        - "locust-results_stderr.json"
        - "response_times.txt"


    - name: Show result
      debug:
        msg: "Results in {{ local_results_dir }}"

- name: Backup configuration files
  hosts: localhost
  tasks:
    - ansible.builtin.copy:
        src: templates/edge-configuration.yaml.j2
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/"
    - ansible.builtin.copy:
        src: templates/cloud-configuration.yaml.j2
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/"
    - ansible.builtin.copy:
        src: locust/locustfile.py
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/"
    - ansible.builtin.copy:
        src: run_experiment.yml
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/"

- name: Backup Serverledge log
  hosts: edge[0]
  tasks:
    - name: Get current invocation ID for serverledge
      ansible.builtin.command:
        cmd: systemctl show serverledge --property=InvocationID --value
      register: invocation_id
      changed_when: false

    - name: Get logs for serverledge since last restart
      ansible.builtin.command:
        cmd: journalctl _SYSTEMD_INVOCATION_ID={{ invocation_id.stdout | trim }} --no-pager
      register: unit_logs
      changed_when: false

    - name: Save logs to local file
      ansible.builtin.copy:
        content: "{{ unit_logs.stdout }}"
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/serverledge.log"
      delegate_to: localhost

    - name: Get current invocation ID for solver
      ansible.builtin.command:
        cmd: systemctl show solver --property=InvocationID --value
      register: invocation_id
      changed_when: false

    - name: Get logs for solver since last restart
      ansible.builtin.command:
        cmd: journalctl _SYSTEMD_INVOCATION_ID={{ invocation_id.stdout | trim }} --no-pager
      register: unit_logs
      changed_when: false

    - name: Save logs to local file
      ansible.builtin.copy:
        content: "{{ unit_logs.stdout }}"
        dest: "{{ hostvars['localhost']['local_results_dir_with_ts'] }}/solver.log"
      delegate_to: localhost
